services:
  nginx:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  server1:
    build: ./server
    env_file:
      - ./server/.env
    environment:
      - SERVER_NAME="FIRST SERVER"
    ports:
      - 9000:3000
  server2:
    build: ./server
    env_file:
      - ./server/.env
    environment:
      - SERVER_NAME="SECOND SERVER"
    ports:
      - 9001:3000
  server3:
    build: ./server
    env_file:
      - ./server/.env
    environment:
      - SERVER_NAME="THIRD SERVER"
    ports:
      - 9002:3000
